name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest flake8

      - name: Lint
        run: flake8 src tests

      - name: Train model
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python src/train.py --version v0.1 --model linear

      - name: Upload metrics artifact
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: artifacts/metrics.json
    

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest -q